### PR TITLE
fixes passing old (oppositte) checked state to the onChange callback

### LINKED ISSUE #59: isChecked parameter of onChange is returning opposite value
When using the onChange prop and passing the _checked_ parameter, the parameter actually return the opposite of what the checked state actually is.

Anyone else getting this issue?

### PR DESCRIPTION
**Pull request by haraldreingruber**
This should fix #59

### CODE REVIEW

**Comment by ncuillery** [comment]
👍 

It's a breaking change but, come on, this module has one job... and it does it wrong.

**Comment by sconxu** [comment]
I encourage you to build a better one that does it good.

**Comment by ncuillery** [comment]
Didn't mean to offense, I apologize.

Thanks for merging this, please can you publish a new version on NPM ? Should be `2.0.0` I guess, because of the breaking change.

**Comment by sconxu** [comment]
I just did that.

**Pull request merged**
