### PR TITLE
Make appearance of checkbox customisable

### PR DESCRIPTION
**Pull request by ExplodingCabbage**
Basically, this pull request:
- Scraps the idea of having an 'enabled' image and a 'disabled' image, instead opting for a 'checkmark' image that gets drawn on top of an ordinary view when the checkbox is checked.
- Allows said view to be styled with CSS

Same as https://github.com/sconxu/react-native-checkbox/pull/15, but I've moved it onto my master branch to make it easier for anyone who wants to to use it pre-merge.

### CODE REVIEW

**Comment by ExplodingCabbage** [comment]
@sconxu why'd you reject this?

**Comment by bogdancarmanus** [comment]
As I'm trying to keep the component as simple to use as possible, I assume it's easier for most of the users to use it as it is, with images. If one has time to create custom container view and style it then she/he can create from scratch her/his own checkbox component. Thanks for being active on this repo and hope you got an answer for your question.

**Comment by ExplodingCabbage** [comment]
I think that's a mistake - it seems wrong to me to think that devs who are styling the rest of their application with CSS will find it more convenient to use a static image (that, given that this PR was rejected, doesn't even get auto-scaled, so that it has to be edited to exactly the right size and provided in multiple sizes if it needs to be used at different scales!) to provide a background and border (which, in 95%+ of cases, is going to be all that's needed besides the check mark itself) than to just use CSS.

But so be it - I'll look into putting my competing fork onto npm under some other name and we can let the users decide.

By the way, on a really petty note, you might want to cherry-pick b073cfd8b7517ee14be21e8d5d0476afbf268352 since it's an outright fix.

**Comment by bogdancarmanus** [comment]
The latest version of this component allows you to customize the checkbox container style as well, so you can already use it the way you want.

**Comment by ExplodingCabbage** [comment]
> The latest version of this component allows you to customize the checkbox container style as well

So it does.

However, the CSS API introduced in https://github.com/sconxu/react-native-checkbox/pull/31 is fairly horrible compared to the one here. A comparison of differences (these are from memory - don't have the opportunity to test right now - so apologies if I'm wrong on some details):

- The current version exposes two style props, `containerStyle` and `checkboxStyle` (with no documentation explaining when to use which one), whereas this PR exposes only one and documents it in detail
- In the current version, passing a value for *any* CSS property within `containerStyle` or `checkboxStyle` nukes all the default styling on that element, so if you want to just, say, add a border to the container without changing anything else, then you need to copy and paste all the default container CSS into your application. In this PR, CSS properties set by the user are merged with the default ones instead of causing the defaults to be ignored entirely.
- In the current version, images are not autoscaled, so have to be provided at exactly the size they are going to be displayed. In this PR, they are autoscaled
- In the current version, adding borders to the container requires doing your own calculation of how to size the image to fit it within the borders without overlapping them. This PR does that work for you.

The bulk of this PR is making CSS simply and cleanly usable; if your objection to it is the removal of the ability to have an `uncheckedImage`, rather than an objection to *allowing* the component to be styled with CSS at all, then I can rename `checkImage` back to `checkedImage` and then add `uncheckedImage` back in in about 3 lines. At that point people who want to use images will be able to, and people who want a clean interface for styling the checkbox with CSS that doesn't require them to read the component source and manually handle bullshit like border offsetting calculations will be able to use the component that way.

Wouldn't such an approach satisfy both of our use cases without the need to fork?

**Pull request closed without merging**
